package com.example.healthcare.peresentation.common.utils

//buttons
const val LOGIN_BTN = "Login"
const val SIGN_BTN = "Sign up"
const val VERIFY_BTN = "Verify"
const val SAVE_BTN = "Save"
//text fields
const val PHONE_INPUT_LABEL = "Phone Number"
const val FIRST_NAME_INPUT_LABEL = "First Name"
const val LAST_NAME_INPUT_LABEL = "Last Name"
const val ADDRESS_INPUT_LABEL = "Address"
const val city_INPUT_LABEL = "City"
const val POSTAL_CODE_INPUT_LABEL = "Postal Code"
const val CLINIC_NAME_INPUT_LABEL = "Clinic name"
const val CLINIC_ADDR_INPUT_LABEL = "Clinic address"
const val CLINIC_city_INPUT_LABEL = "Clinic city"
const val CLINIC_DESCRIPTION_INPUT_LABEL = "Clinic description"
const val DOCTOR_DEGREE_INPUT_LABEL = "Academic education"
const val DOCTOR_SPECIALITY_INPUT_LABEL = "Specialty"
const val DOCTOR_DESCRIPTION_INPUT_LABEL = "Description"
const val AGE_INPUT_LABEL = "Age"
const val WEIGHT_INPUT_LABEL = "Weight"
const val HEIGHT_INPUT_LABEL = "Height"
const val MEDICAL_INPUT_LABEL = "Medical history"
//texts
const val SIGN_IN_NOTICE = "Please Sign in to continue"
const val WELCOME_TXT = "Welcome!"
const val SIGN_UP_NOTICE = "Don't have an account? "
const val LOGIN_NOTICE = "Already have an account? "
const val DOCTOR_TXT= "Doctor"
const val PATIENT_TXT = "Patient"
const val ADMIN_TXT = "Admin"
const val OTP_NOTICE = "Enter the code sent to your phone number"
const val REGISTER_AS_TEXT = "Register As: "